/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AxisMoveCmd {
    float pos;
    float vel;
    float acc;
    float jerk;
    float snap;
    float crackle;
} AxisMoveCmd;

typedef struct _MoveCmd {
    bool has_x;
    AxisMoveCmd x;
    bool has_y;
    AxisMoveCmd y;
    bool has_z;
    AxisMoveCmd z;
    bool has_e;
    AxisMoveCmd e;
} MoveCmd;

typedef struct _Moves {
    pb_size_t move_count;
    MoveCmd move[3];
} Moves;

typedef struct _ConfigSystem {
    float timestep;
    int32_t x_axis_idx;
    int32_t y_axis_idx;
    int32_t z_axis_idx;
    int32_t e_axis_idx;
} ConfigSystem;

typedef struct _SetPID {
    int32_t axis;
    float p;
    float i;
    float d;
    float tf;
} SetPID;

typedef struct _SetParams {
    int32_t axis;
    float phase_r;
    float phase_l;
    float enoder_cpr;
    float counts_per_mm;
} SetParams;

typedef struct _Cmd {
    pb_size_t which_payload;
    union _Cmd_payload {
        Moves moves;
        SetParams axis_params;
        SetPID setpid;
        ConfigSystem config_system;
    } payload;
} Cmd;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AxisMoveCmd_init_default                 {0, 0, 0, 0, 0, 0}
#define MoveCmd_init_default                     {false, AxisMoveCmd_init_default, false, AxisMoveCmd_init_default, false, AxisMoveCmd_init_default, false, AxisMoveCmd_init_default}
#define Moves_init_default                       {0, {MoveCmd_init_default, MoveCmd_init_default, MoveCmd_init_default}}
#define ConfigSystem_init_default                {0, 0, 0, 0, 0}
#define SetPID_init_default                      {0, 0, 0, 0, 0}
#define SetParams_init_default                   {0, 0, 0, 0, 0}
#define Cmd_init_default                         {0, {Moves_init_default}}
#define AxisMoveCmd_init_zero                    {0, 0, 0, 0, 0, 0}
#define MoveCmd_init_zero                        {false, AxisMoveCmd_init_zero, false, AxisMoveCmd_init_zero, false, AxisMoveCmd_init_zero, false, AxisMoveCmd_init_zero}
#define Moves_init_zero                          {0, {MoveCmd_init_zero, MoveCmd_init_zero, MoveCmd_init_zero}}
#define ConfigSystem_init_zero                   {0, 0, 0, 0, 0}
#define SetPID_init_zero                         {0, 0, 0, 0, 0}
#define SetParams_init_zero                      {0, 0, 0, 0, 0}
#define Cmd_init_zero                            {0, {Moves_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define AxisMoveCmd_pos_tag                      1
#define AxisMoveCmd_vel_tag                      2
#define AxisMoveCmd_acc_tag                      3
#define AxisMoveCmd_jerk_tag                     4
#define AxisMoveCmd_snap_tag                     5
#define AxisMoveCmd_crackle_tag                  6
#define MoveCmd_x_tag                            1
#define MoveCmd_y_tag                            2
#define MoveCmd_z_tag                            3
#define MoveCmd_e_tag                            4
#define Moves_move_tag                           1
#define ConfigSystem_timestep_tag                1
#define ConfigSystem_x_axis_idx_tag              2
#define ConfigSystem_y_axis_idx_tag              3
#define ConfigSystem_z_axis_idx_tag              4
#define ConfigSystem_e_axis_idx_tag              5
#define SetPID_axis_tag                          1
#define SetPID_p_tag                             2
#define SetPID_i_tag                             3
#define SetPID_d_tag                             4
#define SetPID_tf_tag                            5
#define SetParams_axis_tag                       1
#define SetParams_phase_r_tag                    2
#define SetParams_phase_l_tag                    3
#define SetParams_enoder_cpr_tag                 4
#define SetParams_counts_per_mm_tag              5
#define Cmd_moves_tag                            1
#define Cmd_axis_params_tag                      2
#define Cmd_setpid_tag                           3
#define Cmd_config_system_tag                    4

/* Struct field encoding specification for nanopb */
#define AxisMoveCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    pos,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    vel,               2) \
X(a, STATIC,   SINGULAR, FLOAT,    acc,               3) \
X(a, STATIC,   SINGULAR, FLOAT,    jerk,              4) \
X(a, STATIC,   SINGULAR, FLOAT,    snap,              5) \
X(a, STATIC,   SINGULAR, FLOAT,    crackle,           6)
#define AxisMoveCmd_CALLBACK NULL
#define AxisMoveCmd_DEFAULT NULL

#define MoveCmd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  x,                 1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  y,                 2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  z,                 3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  e,                 4)
#define MoveCmd_CALLBACK NULL
#define MoveCmd_DEFAULT NULL
#define MoveCmd_x_MSGTYPE AxisMoveCmd
#define MoveCmd_y_MSGTYPE AxisMoveCmd
#define MoveCmd_z_MSGTYPE AxisMoveCmd
#define MoveCmd_e_MSGTYPE AxisMoveCmd

#define Moves_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  move,              1)
#define Moves_CALLBACK NULL
#define Moves_DEFAULT NULL
#define Moves_move_MSGTYPE MoveCmd

#define ConfigSystem_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    timestep,          1) \
X(a, STATIC,   SINGULAR, INT32,    x_axis_idx,        2) \
X(a, STATIC,   SINGULAR, INT32,    y_axis_idx,        3) \
X(a, STATIC,   SINGULAR, INT32,    z_axis_idx,        4) \
X(a, STATIC,   SINGULAR, INT32,    e_axis_idx,        5)
#define ConfigSystem_CALLBACK NULL
#define ConfigSystem_DEFAULT NULL

#define SetPID_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    axis,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    p,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    i,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    d,                 4) \
X(a, STATIC,   SINGULAR, FLOAT,    tf,                5)
#define SetPID_CALLBACK NULL
#define SetPID_DEFAULT NULL

#define SetParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    axis,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    phase_r,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    phase_l,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    enoder_cpr,        4) \
X(a, STATIC,   SINGULAR, FLOAT,    counts_per_mm,     5)
#define SetParams_CALLBACK NULL
#define SetParams_DEFAULT NULL

#define Cmd_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,moves,payload.moves),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,axis_params,payload.axis_params),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,setpid,payload.setpid),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,config_system,payload.config_system),   4)
#define Cmd_CALLBACK NULL
#define Cmd_DEFAULT NULL
#define Cmd_payload_moves_MSGTYPE Moves
#define Cmd_payload_axis_params_MSGTYPE SetParams
#define Cmd_payload_setpid_MSGTYPE SetPID
#define Cmd_payload_config_system_MSGTYPE ConfigSystem

extern const pb_msgdesc_t AxisMoveCmd_msg;
extern const pb_msgdesc_t MoveCmd_msg;
extern const pb_msgdesc_t Moves_msg;
extern const pb_msgdesc_t ConfigSystem_msg;
extern const pb_msgdesc_t SetPID_msg;
extern const pb_msgdesc_t SetParams_msg;
extern const pb_msgdesc_t Cmd_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AxisMoveCmd_fields &AxisMoveCmd_msg
#define MoveCmd_fields &MoveCmd_msg
#define Moves_fields &Moves_msg
#define ConfigSystem_fields &ConfigSystem_msg
#define SetPID_fields &SetPID_msg
#define SetParams_fields &SetParams_msg
#define Cmd_fields &Cmd_msg

/* Maximum encoded size of messages (where known) */
#define AxisMoveCmd_size                         30
#define Cmd_size                                 396
#define ConfigSystem_size                        49
#define MESSAGES_PB_H_MAX_SIZE                   Cmd_size
#define MoveCmd_size                             128
#define Moves_size                               393
#define SetPID_size                              31
#define SetParams_size                           31

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
