/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AxisMoveCmd, AxisMoveCmd, AUTO)


PB_BIND(MoveCmd, MoveCmd, AUTO)


PB_BIND(SetPID, SetPID, AUTO)


PB_BIND(Cmd, Cmd, AUTO)



