/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AxisMoveCmd {
    float pos;
    float vel;
    float acc;
    float jerk;
    float snap;
    float crackle;
} AxisMoveCmd;

typedef struct _MoveCmd {
    bool has_x;
    AxisMoveCmd x;
    bool has_y;
    AxisMoveCmd y;
    bool has_z;
    AxisMoveCmd z;
    bool has_e;
    AxisMoveCmd e;
} MoveCmd;

typedef struct _SetPID {
    int32_t axis;
    float p;
    float i;
    float d;
    float tf;
} SetPID;

typedef struct _Cmd {
    pb_size_t which_payload;
    union _Cmd_payload {
        MoveCmd move;
        SetPID setpid;
    } payload;
} Cmd;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AxisMoveCmd_init_default                 {0, 0, 0, 0, 0, 0}
#define MoveCmd_init_default                     {false, AxisMoveCmd_init_default, false, AxisMoveCmd_init_default, false, AxisMoveCmd_init_default, false, AxisMoveCmd_init_default}
#define SetPID_init_default                      {0, 0, 0, 0, 0}
#define Cmd_init_default                         {0, {MoveCmd_init_default}}
#define AxisMoveCmd_init_zero                    {0, 0, 0, 0, 0, 0}
#define MoveCmd_init_zero                        {false, AxisMoveCmd_init_zero, false, AxisMoveCmd_init_zero, false, AxisMoveCmd_init_zero, false, AxisMoveCmd_init_zero}
#define SetPID_init_zero                         {0, 0, 0, 0, 0}
#define Cmd_init_zero                            {0, {MoveCmd_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define AxisMoveCmd_pos_tag                      1
#define AxisMoveCmd_vel_tag                      2
#define AxisMoveCmd_acc_tag                      3
#define AxisMoveCmd_jerk_tag                     4
#define AxisMoveCmd_snap_tag                     5
#define AxisMoveCmd_crackle_tag                  6
#define MoveCmd_x_tag                            1
#define MoveCmd_y_tag                            2
#define MoveCmd_z_tag                            3
#define MoveCmd_e_tag                            4
#define SetPID_axis_tag                          1
#define SetPID_p_tag                             2
#define SetPID_i_tag                             3
#define SetPID_d_tag                             4
#define SetPID_tf_tag                            5
#define Cmd_move_tag                             1
#define Cmd_setpid_tag                           2

/* Struct field encoding specification for nanopb */
#define AxisMoveCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    pos,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    vel,               2) \
X(a, STATIC,   SINGULAR, FLOAT,    acc,               3) \
X(a, STATIC,   SINGULAR, FLOAT,    jerk,              4) \
X(a, STATIC,   SINGULAR, FLOAT,    snap,              5) \
X(a, STATIC,   SINGULAR, FLOAT,    crackle,           6)
#define AxisMoveCmd_CALLBACK NULL
#define AxisMoveCmd_DEFAULT NULL

#define MoveCmd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  x,                 1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  y,                 2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  z,                 3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  e,                 4)
#define MoveCmd_CALLBACK NULL
#define MoveCmd_DEFAULT NULL
#define MoveCmd_x_MSGTYPE AxisMoveCmd
#define MoveCmd_y_MSGTYPE AxisMoveCmd
#define MoveCmd_z_MSGTYPE AxisMoveCmd
#define MoveCmd_e_MSGTYPE AxisMoveCmd

#define SetPID_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    axis,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    p,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    i,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    d,                 4) \
X(a, STATIC,   SINGULAR, FLOAT,    tf,                5)
#define SetPID_CALLBACK NULL
#define SetPID_DEFAULT NULL

#define Cmd_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,move,payload.move),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,setpid,payload.setpid),   2)
#define Cmd_CALLBACK NULL
#define Cmd_DEFAULT NULL
#define Cmd_payload_move_MSGTYPE MoveCmd
#define Cmd_payload_setpid_MSGTYPE SetPID

extern const pb_msgdesc_t AxisMoveCmd_msg;
extern const pb_msgdesc_t MoveCmd_msg;
extern const pb_msgdesc_t SetPID_msg;
extern const pb_msgdesc_t Cmd_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AxisMoveCmd_fields &AxisMoveCmd_msg
#define MoveCmd_fields &MoveCmd_msg
#define SetPID_fields &SetPID_msg
#define Cmd_fields &Cmd_msg

/* Maximum encoded size of messages (where known) */
#define AxisMoveCmd_size                         30
#define Cmd_size                                 131
#define MESSAGES_PB_H_MAX_SIZE                   Cmd_size
#define MoveCmd_size                             128
#define SetPID_size                              31

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
